### ISSUE TITLE
remove magitech techtree

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#11]
I thought it would be a good idea to separate the magitech techree from the distribution and having it available as a separate download from the "game mods" menu.

Is it even worth maintaining it? There's already a Magic and Tech faction in zetapack.  The magitech tech tree is basically the unaltered tech tree from Glest?

Agree? Disagree?

**Comment by andy5995** [comment]
I see it's just using faction links and uses 216K

The faction links will need to be changed so it links to to the magic and tech factions in zetapack

**Comment by Jammyjamjamman** [comment]
Short answer IMO is that it's not worth maintaining.

I think its original purpose was to create a "classic glest" environment, but I think the link solution fails to do this anyway because they're not the same factions as in original glest.

A better solution would be to create a factions based off megapack's which contain xml that  _override_ those already present to create original glest (but this is another project). I would, however, rate this as low priority.

**Comment by andy5995** [comment]
I agree we can remove the magitech directory. I'll take care of it.

As for your other suggestion.. I'm guessing we don't need a ticket for that. If you feel like doing it in the future, you'll either do it or open a ticket. :)
